-- Ownership transfer infrastructure
-- Revised Architecture: Identity != Access != Participation

create table if not exists public.trip_ownership_transfers (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  previous_owner_user_id uuid not null references auth.users(id),
  new_owner_user_id uuid not null references auth.users(id),
  actor_user_id uuid not null references auth.users(id),
  reason text null,
  created_at timestamptz not null default now()
);

create index if not exists trip_ownership_transfers_trip_id_created_at_idx
on public.trip_ownership_transfers (trip_id, created_at desc);

create or replace function public.transfer_trip_ownership(
  p_trip_id bigint,
  p_new_owner_user_id uuid,
  p_transfer_reason text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_previous_owner_user_id uuid;
  v_target_is_active_editor boolean;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'You must be signed in to transfer ownership.';
  end if;

  select user_id
  into v_previous_owner_user_id
  from public.trips
  where id = p_trip_id
  for update;

  if v_previous_owner_user_id is null then
    raise exception 'Trip not found.';
  end if;

  if v_previous_owner_user_id <> v_actor_user_id then
    raise exception 'Only the current owner can transfer ownership.';
  end if;

  if p_new_owner_user_id = v_previous_owner_user_id then
    raise exception 'This user is already the owner.';
  end if;

  select exists (
    select 1
    from public.trip_collaborators
    where trip_id = p_trip_id
      and user_id = p_new_owner_user_id
      and active = true
      and role = 'editor'
  )
  into v_target_is_active_editor;

  if not v_target_is_active_editor then
    raise exception 'Ownership can only be transferred to an active editor.';
  end if;

  update public.trips
  set user_id = p_new_owner_user_id
  where id = p_trip_id;

  insert into public.trip_members (trip_id, user_id, name, active)
  select p_trip_id, p_new_owner_user_id, coalesce(p.display_name, p.email, 'Owner'), true
  from public.profiles p
  where p.user_id = p_new_owner_user_id
  on conflict do nothing;

  insert into public.trip_members (trip_id, user_id, name, active)
  select p_trip_id, v_previous_owner_user_id, coalesce(p.display_name, p.email, 'Editor'), true
  from public.profiles p
  where p.user_id = v_previous_owner_user_id
  on conflict do nothing;

  insert into public.trip_collaborators (trip_id, user_id, role, active, removed_at)
  values (p_trip_id, v_previous_owner_user_id, 'editor', true, null)
  on conflict do nothing;

  insert into public.trip_ownership_transfers (
    trip_id,
    previous_owner_user_id,
    new_owner_user_id,
    actor_user_id,
    reason
  )
  values (
    p_trip_id,
    v_previous_owner_user_id,
    p_new_owner_user_id,
    v_actor_user_id,
    p_transfer_reason
  );

  insert into public.trip_activity_log (
    trip_id,
    actor_user_id,
    event_type,
    target_type,
    target_id,
    metadata
  )
  values (
    p_trip_id,
    v_actor_user_id,
    'ownership_transferred',
    'ownership',
    p_trip_id,
    jsonb_build_object(
      'previous_owner_user_id', v_previous_owner_user_id,
      'new_owner_user_id', p_new_owner_user_id,
      'reason', p_transfer_reason
    )
  );
end;
$$;

grant execute on function public.transfer_trip_ownership(bigint, uuid, text) to authenticated;
